name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr)
variables:
  CI_NAME: Azure Pipelines
  CI_BUILD_ID: $(Build.BuildId)
  CI_BUILD_URL: "https://dev.azure.com/poliastro/poliastro/_build/results?buildId=$(Build.BuildId)"
  CIBW_BUILD: cp37-* cp38-*
  CIBW_SKIP: "*-win32 *-manylinux1_i686"
  CODECOV_TOKEN: "0d87eeea-9528-4c59-b23f-0aedb3cc76a3"

resources:
  repositories:
  - repository: OpenAstronomy
    type: github
    endpoint: poliastro
    name: OpenAstronomy/azure-pipelines-templates
    ref: master             # Referenced to the "Master" branch in the Open Astronomy Repository 

trigger:
  branches:
    include:
    - '*'
    exclude:
    - '*backport*'
  tags:
    include:
    - 'v*'
    exclude:
    - '*dev*'
    - '*pre*'
    - '*post*'

jobs:
- template: run-tox-env.yml@OpenAstronomy
  parameters:
    submodules: false
    env:
      - PIP_PREFER_BINARY: true
      - PIP_PROGRESS_BAR: "off"
      - MPLBACKEND: Agg
      - FLIT_ROOT_INSTALL: 1
    posargs: '-vv'
    envs:
      - linux: check
        name : quality

      - linux: py37
        name: py37_test

      - linux: py38-fast
        name: py38_fast_test

      - linux: py38-online
        name: py38_online_test

      - linux: py38-slow
        name: py38_slow

      - linux: py38-images
        name: py38_images

      - linux: py38-coverage
        name: coverage
        coverage: codecov
        posargs: --cov-report=term-missing

      - linux: py39
        name: py39_test

      - windows: py38
        name: py38_test_windows

      - macos: py38
        name: py38_test_macos

- template: run-tox-env.yml@OpenAstronomy
  parameters:
    default_python: 3.8
    submodules: false
    env:
      - PIP_PREFER_BINARY: true
      - PIP_PROGRESS_BAR: "off"
      - MPLBACKEND: Agg
      - FLIT_ROOT_INSTALL: 1
    posargs: '-vv'
    libraries:
      apt:
        - pandoc
    envs:
      - linux: docs
        name: docs_test

- template: publish.yml@OpenAstronomy
  parameters:
    ${{ if startsWith(variables.Build.SourceBranch, 'refs/tags/v') }}:
      pypi_connection_name: 'pypi_upload'
    test_extras: 'dev'
    test_command: 'cd $(Build.SourcesDirectory)/tests; pytest -m "not slow and not mpl_image_compare"'
    targets:
    - sdist
    - wheels_universal
